name: Native Image

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v2.1.3

defaults:
  run:
    shell: bash

jobs:
  workflow_config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - name: Generate native image
        run: |
          docker build -t umlet-native -f ./umlet-cli/Dockerfile ./umlet-cli 
          docker create --name umlet-native-binary umlet-native
          docker cp umlet-native-binary:./umlet umlet
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create release
        run: |
          gh release create $RELEASE_VERSION './umlet#UMlet native image (Linux amd64)'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
